### ISSUE TITLE
App is crashing?

### ISSUE THREAD

**Issue by dnemet** [TimFelixBeyer/FaceExplorer#2]
I downloaded app v.0.0.3 and allowed full access to my photos library. After that the app crashes. I know nothing about GitHub and custom apps so any help you could provide would be great. I've been trying to organize faces in photos for years and no products seem to work so I'm very excited to try this out!

**Comment by TimFelixBeyer** [comment]
Happy to hear of your interest! 
To fix the issue it would help to know some details like the macOS version (Apple Symbol in the top left -> About this Mac), and the macOS Photos version (Open Photos, click on „Photos“ in the top menubar -> „About Photos“)
Thanks!

**Comment by dnemet** [comment]
macOS is Sonoma 14.3.1 and Photos is Version 9.0 (630.0.150)

**Comment by TimFelixBeyer** [comment]
I was unable to replicate the issue with the same macOS/Photos versions.
However, it would be great if you could try again with the just-released v0.0.4 which has improved error handling and may fix the problem.

**Comment by pensphreak** [comment]
I have the same problem with 0.0.4.  macOS Sonoma 14.5 (23F79) and Photos 9.0 (651.0.100)

**Comment by hmlj** [comment]
> I have the same problem with 0.0.4. macOS Sonoma 14.5 (23F79) and Photos 9.0 (651.0.100)

Same. Set photo library on initial launch and then it crashed. Now crashes at launch.

Not great with the crash reports, but I can provide.

**Comment by TimFelixBeyer** [comment]
> Not great with the crash reports, but I can provide.

@hmlj If possible, please send the report to my email address at tim.beyer@tum.de and I will take a look. 
I'm sure there is a better way to gather crash reports, so if you know please inform me.

**Comment by TimFelixBeyer** [comment]
@hmlj @pensphreak @dnemet Please feel free to retry with the newest version v0.0.6 which fixes a significant bug.

**Comment by dnemet** [comment]
The new release is working. Thank you!
